CREATE USER $MYSQL_USER@"localhost" IDENTIFIED BY $MYSQL_PASSWORD;
GRANT ALL PRIVILEGES ON * . * TO $MYSQL_USER@"localhost";

CREATE USER $MYSQL_USER@"%" IDENTIFIED BY $MYSQL_PASSWORD;
GRANT ALL PRIVILEGES ON * . * TO $MYSQL_USER@"%";

FLUSH PRIVILEGES;
