version: '3.8'

volumes:
    dados-db-acesso-adm:      

services:
  db-onstores:
    container_name: "db-acesso-adm"
    image: "mysql"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306
    expose:
      - 3306
    volumes: 
      - dados-db-acesso-adm:/var/lib/mysql
